# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5db27e081e14a7d0b3de28d20d95d45390333f6eb2b72412fd267840243d308ad78553ff877fe22774b61e08d91f3e8b325806763e3db92e4d7a9f8600b92a5b

test:
  secret_key_base: aa4be07f5967427285bf192aab50e60d7379d0f7b4ccdeea163df58b11632856a533e490f3f9b66a61d17e93640fcfd6cc6bc9e8fb82aef337230630483dd855

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
